version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:8080"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DoAn_HotelBookingContext=Server=db;Database=HotelBookingDb;User Id=sa;Password=YourPassword123;TrustServerCertificate=True;
  
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourPassword123
    ports:
      - "1433:1433"