// <auto-generated />
using System;
using DoAn_HotelBooking.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DoAn_HotelBooking.Migrations
{
    [DbContext(typeof(DoAn_HotelBookingContext))]
    [Migration("20260617044401_CreateDB")]
    partial class CreateDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DoAn_HotelBooking.Models.DanhGiaKS", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("MaKhachSan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaTaiKhoan")
                        .HasColumnType("integer");

                    b.Property<int>("SoSao")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("MaKhachSan");

                    b.HasIndex("MaTaiKhoan");

                    b.ToTable("DanhGiaKS");
                });

            modelBuilder.Entity("DoAn_HotelBooking.Models.DanhGiaPhong", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("MaPhong")
                        .HasColumnType("integer");

                    b.Property<int>("MaTaiKhoan")
                        .HasColumnType("integer");

                    b.Property<int>("SoSao")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("MaPhong");

                    b.HasIndex("MaTaiKhoan");

                    b.ToTable("DanhGiaPhong");
                });

            modelBuilder.Entity("DoAn_HotelBooking.Models.DatPhong", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<int>("MaPhong")
                        .HasColumnType("integer");

                    b.Property<int>("MaTaiKhoan")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayNhanPhong")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTraPhong")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SoNguoi")
                        .HasColumnType("integer");

                    b.Property<decimal>("TienGiam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThaiDatPhong")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TrangThaiThanhToan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("MaPhong");

                    b.HasIndex("MaTaiKhoan");

                    b.ToTable("DatPhong");
                });

            modelBuilder.Entity("DoAn_HotelBooking.Models.HangThanhVien", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("MocDiemToiThieu")
                        .HasColumnType("integer");

                    b.Property<string>("TenHang")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TyLeGiamGia")
                        .HasColumnType("double precision");

                    b.HasKey("ID");

                    b.ToTable("HangThanhVien");
                });

            modelBuilder.Entity("DoAn_HotelBooking.Models.KhachSan", b =>
                {
                    b.Property<string>("MaKhachSan")
                        .HasColumnType("text");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KinhDo")
                        .HasColumnType("text");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenKhachSan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ViDo")
                        .HasColumnType("text");

                    b.HasKey("MaKhachSan");

                    b.ToTable("KhachSan");
                });

            modelBuilder.Entity("DoAn_HotelBooking.Models.Phong", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<decimal>("GiaPhong")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LoaiPhong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MaKhachSan")
                        .HasColumnType("text");

                    b.Property<int>("SoPhong")
                        .HasColumnType("integer");

                    b.Property<int>("SucChua")
                        .HasColumnType("integer");

                    b.Property<int>("Tang")
                        .HasColumnType("integer");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("ID");

                    b.HasIndex("MaKhachSan");

                    b.ToTable("Phong");
                });

            modelBuilder.Entity("DoAn_HotelBooking.Models.SystemLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("DaXuLy")
                        .HasColumnType("boolean");

                    b.Property<string>("Exception")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("SystemLogs");
                });

            modelBuilder.Entity("DoAn_HotelBooking.Models.TaiKhoan", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("DiemTichLuy")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HoVaTen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("MaHang")
                        .HasColumnType("integer");

                    b.Property<string>("MaKhachSan")
                        .HasColumnType("text");

                    b.Property<string>("MatKhau")
                        .HasColumnType("text");

                    b.Property<string>("QuyenHan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("MaHang");

                    b.HasIndex("MaKhachSan");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("TaiKhoan");
                });

            modelBuilder.Entity("DoAn_HotelBooking.Models.ThongBao", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<bool>("DaDoc")
                        .HasColumnType("boolean");

                    b.Property<string>("MaKhachSan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("ThongBao");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("DoAn_HotelBooking.Models.DanhGiaKS", b =>
                {
                    b.HasOne("DoAn_HotelBooking.Models.KhachSan", "KhachSan")
                        .WithMany("DanhGiaKhachSans")
                        .HasForeignKey("MaKhachSan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAn_HotelBooking.Models.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("MaTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachSan");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("DoAn_HotelBooking.Models.DanhGiaPhong", b =>
                {
                    b.HasOne("DoAn_HotelBooking.Models.Phong", "Phong")
                        .WithMany("DanhGiaPhongs")
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAn_HotelBooking.Models.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("MaTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phong");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("DoAn_HotelBooking.Models.DatPhong", b =>
                {
                    b.HasOne("DoAn_HotelBooking.Models.Phong", "Phong")
                        .WithMany("DatPhongs")
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAn_HotelBooking.Models.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("MaTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phong");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("DoAn_HotelBooking.Models.Phong", b =>
                {
                    b.HasOne("DoAn_HotelBooking.Models.KhachSan", "KhachSan")
                        .WithMany("Phongs")
                        .HasForeignKey("MaKhachSan");

                    b.Navigation("KhachSan");
                });

            modelBuilder.Entity("DoAn_HotelBooking.Models.TaiKhoan", b =>
                {
                    b.HasOne("DoAn_HotelBooking.Models.HangThanhVien", "HangThanhVien")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("MaHang");

                    b.HasOne("DoAn_HotelBooking.Models.KhachSan", "KhachSan")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("MaKhachSan");

                    b.Navigation("HangThanhVien");

                    b.Navigation("KhachSan");
                });

            modelBuilder.Entity("DoAn_HotelBooking.Models.HangThanhVien", b =>
                {
                    b.Navigation("TaiKhoans");
                });

            modelBuilder.Entity("DoAn_HotelBooking.Models.KhachSan", b =>
                {
                    b.Navigation("DanhGiaKhachSans");

                    b.Navigation("Phongs");

                    b.Navigation("TaiKhoans");
                });

            modelBuilder.Entity("DoAn_HotelBooking.Models.Phong", b =>
                {
                    b.Navigation("DanhGiaPhongs");

                    b.Navigation("DatPhongs");
                });
#pragma warning restore 612, 618
        }
    }
}
