// <auto-generated />
using System;
using DoAn_HotelBooking.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DoAn_HotelBooking.Migrations
{
    [DbContext(typeof(DoAn_HotelBookingContext))]
    partial class DoAn_HotelBookingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DoAn_HotelBooking.Models.DanhGiaKS", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("MaKhachSan")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<int>("SoSao")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MaKhachSan");

                    b.HasIndex("MaTaiKhoan");

                    b.ToTable("DanhGiaKS");
                });

            modelBuilder.Entity("DoAn_HotelBooking.Models.DanhGiaPhong", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("MaPhong")
                        .HasColumnType("int");

                    b.Property<int>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<int>("SoSao")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MaPhong");

                    b.HasIndex("MaTaiKhoan");

                    b.ToTable("DanhGiaPhong");
                });

            modelBuilder.Entity("DoAn_HotelBooking.Models.DatPhong", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaPhong")
                        .HasColumnType("int");

                    b.Property<int>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayNhanPhong")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTraPhong")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoNguoi")
                        .HasColumnType("int");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThaiDatPhong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThaiThanhToan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("MaPhong");

                    b.HasIndex("MaTaiKhoan");

                    b.ToTable("DatPhong");
                });

            modelBuilder.Entity("DoAn_HotelBooking.Models.KhachSan", b =>
                {
                    b.Property<string>("MaKhachSan")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KinhDo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKhachSan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ViDo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaKhachSan");

                    b.ToTable("KhachSan");
                });

            modelBuilder.Entity("DoAn_HotelBooking.Models.Phong", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("GiaPhong")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiPhong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaKhachSan")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SoPhong")
                        .HasColumnType("int");

                    b.Property<int>("SucChua")
                        .HasColumnType("int");

                    b.Property<int>("Tang")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.HasIndex("MaKhachSan");

                    b.ToTable("Phong");
                });

            modelBuilder.Entity("DoAn_HotelBooking.Models.TaiKhoan", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("DiemTichLuy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoVaTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaKhachSan")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MatKhau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuyenHan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("MaKhachSan");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("TaiKhoan");
                });

            modelBuilder.Entity("DoAn_HotelBooking.Models.DanhGiaKS", b =>
                {
                    b.HasOne("DoAn_HotelBooking.Models.KhachSan", "KhachSan")
                        .WithMany("DanhGiaKhachSans")
                        .HasForeignKey("MaKhachSan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAn_HotelBooking.Models.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("MaTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachSan");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("DoAn_HotelBooking.Models.DanhGiaPhong", b =>
                {
                    b.HasOne("DoAn_HotelBooking.Models.Phong", "Phong")
                        .WithMany("DanhGiaPhongs")
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAn_HotelBooking.Models.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("MaTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phong");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("DoAn_HotelBooking.Models.DatPhong", b =>
                {
                    b.HasOne("DoAn_HotelBooking.Models.Phong", "Phong")
                        .WithMany("DatPhongs")
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAn_HotelBooking.Models.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("MaTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phong");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("DoAn_HotelBooking.Models.Phong", b =>
                {
                    b.HasOne("DoAn_HotelBooking.Models.KhachSan", "KhachSan")
                        .WithMany("Phongs")
                        .HasForeignKey("MaKhachSan");

                    b.Navigation("KhachSan");
                });

            modelBuilder.Entity("DoAn_HotelBooking.Models.TaiKhoan", b =>
                {
                    b.HasOne("DoAn_HotelBooking.Models.KhachSan", "KhachSan")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("MaKhachSan");

                    b.Navigation("KhachSan");
                });

            modelBuilder.Entity("DoAn_HotelBooking.Models.KhachSan", b =>
                {
                    b.Navigation("DanhGiaKhachSans");

                    b.Navigation("Phongs");

                    b.Navigation("TaiKhoans");
                });

            modelBuilder.Entity("DoAn_HotelBooking.Models.Phong", b =>
                {
                    b.Navigation("DanhGiaPhongs");

                    b.Navigation("DatPhongs");
                });
#pragma warning restore 612, 618
        }
    }
}
